services:
  bitcoind:
    image: bitcoin/bitcoin:27.1
    command:
      - -regtest
      - -server=1
      - -txindex=1
      - -fallbackfee=0.0002
      - -rpcuser=regtest
      - -rpcpassword=regtest
      - -rpcbind=0.0.0.0
      - -rpcallowip=0.0.0.0/0
      - -zmqpubrawblock=tcp://0.0.0.0:28332
      - -zmqpubrawtx=tcp://0.0.0.0:28333
      - -printtoconsole
    volumes:
      - lightning-regtest-bitcoind:/home/bitcoin/.bitcoin # allow-local-path: container data directory

  cln-receiver:
    image: elementsproject/lightningd:latest
    depends_on:
      - bitcoind
    command:
      - --network=regtest
      - --bitcoin-rpcconnect=bitcoind
      - --bitcoin-rpcport=18443
      - --bitcoin-rpcuser=regtest
      - --bitcoin-rpcpassword=regtest
      - --addr=0.0.0.0:9735
      - --announce-addr=cln-receiver:9735
      - --log-level=debug
    volumes:
      - lightning-regtest-cln-receiver:/root/.lightning

  cln-payer:
    image: elementsproject/lightningd:latest
    depends_on:
      - bitcoind
    command:
      - --network=regtest
      - --bitcoin-rpcconnect=bitcoind
      - --bitcoin-rpcport=18443
      - --bitcoin-rpcuser=regtest
      - --bitcoin-rpcpassword=regtest
      - --addr=0.0.0.0:9735
      - --announce-addr=cln-payer:9735
      - --log-level=debug
    volumes:
      - lightning-regtest-cln-payer:/root/.lightning

volumes:
  lightning-regtest-bitcoind:
  lightning-regtest-cln-receiver:
  lightning-regtest-cln-payer:
